import { SingleUserResponse, UpdateUserRequest, User } from "@/store/user/types/singleUser";
import { AdminUser } from "@/store/user/types/user";
import { useEffect, useState } from "react";

export const mockDashboardStats = {
  totalUsers: 1250,
  totalUsersChange: "+12% from last month",
  activeToday: 320,
  activeTodayChange: "+5% from yesterday",
  labReports: 85,
  labReportsChange: "+8% from last week",
  aiConversations: 450,
  aiConversationsChange: "+15% from last week",
};

export type MockUserRecord = AdminUser & { fullDetail: User };

export const initialMockUsers: MockUserRecord[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    status: "active",
    devices: "Apple Watch, iPhone 15",
    joinDate: "2024-05-12T10:00:00.000Z",
    lastActive: "2025-10-04T09:30:00.000Z",
    fullDetail: {
      id: "1",
      email: "john.doe@example.com",
      role: "USER",
      phone: "+1 (555) 123-4567",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-05-12T10:00:00.000Z",
      updatedAt: "2025-10-04T09:30:00.000Z",
      lastActive: "2025-10-04T09:30:00.000Z",
      status: "active",
      profile: {
        id: "p-1",
        userId: "1",
        photo: null,
        fullName: "John Doe",
        isEnableNotification: true,
        language: "EN",
        dateOfBirth: "1998-05-14",
        gender: "MALE",
        height: 180,
        weight: 78,
        healthGoal: "LOSE_WEIGHT",
        createdAt: "2024-05-12T10:00:00.000Z",
        updatedAt: "2025-10-04T09:30:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-1",
        userId: "1",
        doNotDisturb: false,
        systemAlerts: true,
        personalizedNudges: true,
        wellnessNudges: true,
        createdAt: "2024-05-12T10:00:00.000Z",
        updatedAt: "2025-10-04T09:30:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Apple Watch", "iPhone 15"],
    },
  },
  {
    id: "2",
    name: "Sarah Smith",
    email: "sarah.smith@example.com",
    status: "active",
    devices: "Fitbit Charge 5",
    joinDate: "2024-06-20T11:15:00.000Z",
    lastActive: "2025-10-04T08:45:00.000Z",
    fullDetail: {
      id: "2",
      email: "sarah.smith@example.com",
      role: "USER",
      phone: "+1 (555) 234-5678",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-06-20T11:15:00.000Z",
      updatedAt: "2025-10-04T08:45:00.000Z",
      lastActive: "2025-10-04T08:45:00.000Z",
      status: "active",
      profile: {
        id: "p-2",
        userId: "2",
        photo: null,
        fullName: "Sarah Smith",
        isEnableNotification: true,
        language: "EN",
        dateOfBirth: "1995-08-22",
        gender: "FEMALE",
        height: 165,
        weight: 60,
        healthGoal: "IMPROVE_FITNESS",
        createdAt: "2024-06-20T11:15:00.000Z",
        updatedAt: "2025-10-04T08:45:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-2",
        userId: "2",
        doNotDisturb: false,
        systemAlerts: true,
        personalizedNudges: true,
        wellnessNudges: true,
        createdAt: "2024-06-20T11:15:00.000Z",
        updatedAt: "2025-10-04T08:45:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Fitbit Charge 5"],
    },
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike.johnson@example.com",
    status: "inactive",
    devices: "Garmin Forerunner",
    joinDate: "2024-02-10T14:20:00.000Z",
    lastActive: "2025-09-15T16:00:00.000Z",
    fullDetail: {
      id: "3",
      email: "mike.johnson@example.com",
      role: "USER",
      phone: "+1 (555) 345-6789",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-02-10T14:20:00.000Z",
      updatedAt: "2025-09-15T16:00:00.000Z",
      lastActive: "2025-09-15T16:00:00.000Z",
      status: "inactive",
      profile: {
        id: "p-3",
        userId: "3",
        photo: null,
        fullName: "Mike Johnson",
        isEnableNotification: false,
        language: "EN",
        dateOfBirth: "1989-11-30",
        gender: "MALE",
        height: 175,
        weight: 85,
        healthGoal: "BUILD_MUSCLE",
        createdAt: "2024-02-10T14:20:00.000Z",
        updatedAt: "2025-09-15T16:00:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-3",
        userId: "3",
        doNotDisturb: true,
        systemAlerts: false,
        personalizedNudges: false,
        wellnessNudges: false,
        createdAt: "2024-02-10T14:20:00.000Z",
        updatedAt: "2025-09-15T16:00:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Garmin Forerunner"],
    },
  },
  {
    id: "4",
    name: "Emily Brown",
    email: "emily.brown@example.com",
    status: "active",
    devices: "Apple Watch Series 9",
    joinDate: "2024-07-01T09:00:00.000Z",
    lastActive: "2025-10-03T18:20:00.000Z",
    fullDetail: {
      id: "4",
      email: "emily.brown@example.com",
      role: "USER",
      phone: "+1 (555) 456-7890",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-07-01T09:00:00.000Z",
      updatedAt: "2025-10-03T18:20:00.000Z",
      lastActive: "2025-10-03T18:20:00.000Z",
      status: "active",
      profile: {
        id: "p-4",
        userId: "4",
        photo: null,
        fullName: "Emily Brown",
        isEnableNotification: true,
        language: "EN",
        dateOfBirth: "1994-03-12",
        gender: "FEMALE",
        height: 170,
        weight: 64,
        healthGoal: "MAINTAIN_WEIGHT",
        createdAt: "2024-07-01T09:00:00.000Z",
        updatedAt: "2025-10-03T18:20:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-4",
        userId: "4",
        doNotDisturb: false,
        systemAlerts: true,
        personalizedNudges: true,
        wellnessNudges: true,
        createdAt: "2024-07-01T09:00:00.000Z",
        updatedAt: "2025-10-03T18:20:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Apple Watch Series 9"],
    },
  },
  {
    id: "5",
    name: "David Lee",
    email: "david.lee@example.com",
    status: "active",
    devices: "Samsung Galaxy Watch",
    joinDate: "2024-03-14T12:00:00.000Z",
    lastActive: "2025-10-04T07:10:00.000Z",
    fullDetail: {
      id: "5",
      email: "david.lee@example.com",
      role: "USER",
      phone: "+1 (555) 567-8901",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-03-14T12:00:00.000Z",
      updatedAt: "2025-10-04T07:10:00.000Z",
      lastActive: "2025-10-04T07:10:00.000Z",
      status: "active",
      profile: {
        id: "p-5",
        userId: "5",
        photo: null,
        fullName: "David Lee",
        isEnableNotification: true,
        language: "EN",
        dateOfBirth: "1991-09-05",
        gender: "MALE",
        height: 176,
        weight: 73,
        healthGoal: "IMPROVE_FITNESS",
        createdAt: "2024-03-14T12:00:00.000Z",
        updatedAt: "2025-10-04T07:10:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-5",
        userId: "5",
        doNotDisturb: false,
        systemAlerts: true,
        personalizedNudges: true,
        wellnessNudges: true,
        createdAt: "2024-03-14T12:00:00.000Z",
        updatedAt: "2025-10-04T07:10:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Samsung Galaxy Watch"],
    },
  },
  {
    id: "6",
    name: "Jessica Taylor",
    email: "jessica.t@example.com",
    status: "inactive",
    devices: "Whoop 4.0",
    joinDate: "2024-04-18T15:30:00.000Z",
    lastActive: "2025-08-22T10:00:00.000Z",
    fullDetail: {
      id: "6",
      email: "jessica.t@example.com",
      role: "USER",
      phone: "+1 (555) 678-9012",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-04-18T15:30:00.000Z",
      updatedAt: "2025-08-22T10:00:00.000Z",
      lastActive: "2025-08-22T10:00:00.000Z",
      status: "inactive",
      profile: {
        id: "p-6",
        userId: "6",
        photo: null,
        fullName: "Jessica Taylor",
        isEnableNotification: false,
        language: "EN",
        dateOfBirth: "1996-01-19",
        gender: "FEMALE",
        height: 168,
        weight: 58,
        healthGoal: "LOSE_WEIGHT",
        createdAt: "2024-04-18T15:30:00.000Z",
        updatedAt: "2025-08-22T10:00:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-6",
        userId: "6",
        doNotDisturb: true,
        systemAlerts: false,
        personalizedNudges: false,
        wellnessNudges: false,
        createdAt: "2024-04-18T15:30:00.000Z",
        updatedAt: "2025-08-22T10:00:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Whoop 4.0"],
    },
  },
  {
    id: "7",
    name: "Alex Wilson",
    email: "alex.wilson@example.com",
    status: "active",
    devices: "Apple Watch Ultra",
    joinDate: "2024-08-05T08:00:00.000Z",
    lastActive: "2025-10-04T06:50:00.000Z",
    fullDetail: {
      id: "7",
      email: "alex.wilson@example.com",
      role: "USER",
      phone: "+1 (555) 789-0123",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-08-05T08:00:00.000Z",
      updatedAt: "2025-10-04T06:50:00.000Z",
      lastActive: "2025-10-04T06:50:00.000Z",
      status: "active",
      profile: {
        id: "p-7",
        userId: "7",
        photo: null,
        fullName: "Alex Wilson",
        isEnableNotification: true,
        language: "EN",
        dateOfBirth: "1992-07-28",
        gender: "MALE",
        height: 182,
        weight: 82,
        healthGoal: "BUILD_MUSCLE",
        createdAt: "2024-08-05T08:00:00.000Z",
        updatedAt: "2025-10-04T06:50:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-7",
        userId: "7",
        doNotDisturb: false,
        systemAlerts: true,
        personalizedNudges: true,
        wellnessNudges: true,
        createdAt: "2024-08-05T08:00:00.000Z",
        updatedAt: "2025-10-04T06:50:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Apple Watch Ultra"],
    },
  },
  {
    id: "8",
    name: "Sophia Martinez",
    email: "sophia.m@example.com",
    status: "active",
    devices: "Fitbit Versa 4",
    joinDate: "2024-09-11T13:40:00.000Z",
    lastActive: "2025-10-03T21:15:00.000Z",
    fullDetail: {
      id: "8",
      email: "sophia.m@example.com",
      role: "USER",
      phone: "+1 (555) 890-1234",
      firebaseUid: null,
      appleId: null,
      password: null,
      fcmtoken: null,
      refreshToken: null,
      fitbitAccessToken: null,
      fitbitRefreshToken: null,
      fitbitAccessTokenExpiry: null,
      stravaAccessToken: null,
      stravaRefreshToken: null,
      stravaAccessTokenExpiry: null,
      isAgreeTerms: true,
      otp: null,
      otpExpiry: null,
      isDeleted: false,
      changePasswordAt: null,
      createdAt: "2024-09-11T13:40:00.000Z",
      updatedAt: "2025-10-03T21:15:00.000Z",
      lastActive: "2025-10-03T21:15:00.000Z",
      status: "active",
      profile: {
        id: "p-8",
        userId: "8",
        photo: null,
        fullName: "Sophia Martinez",
        isEnableNotification: true,
        language: "ES",
        dateOfBirth: "1997-04-16",
        gender: "FEMALE",
        height: 162,
        weight: 55,
        healthGoal: "IMPROVE_FITNESS",
        createdAt: "2024-09-11T13:40:00.000Z",
        updatedAt: "2025-10-03T21:15:00.000Z",
      },
      deviceIntegration: null,
      notificationSettings: {
        id: "n-8",
        userId: "8",
        doNotDisturb: false,
        systemAlerts: true,
        personalizedNudges: true,
        wellnessNudges: true,
        createdAt: "2024-09-11T13:40:00.000Z",
        updatedAt: "2025-10-03T21:15:00.000Z",
      },
      nudges: [],
      meals: [],
      labReports: [],
      MedicalReports: [],
      conversations: [],
      HealthDatas: [],
      chats: [],
      devices: ["Fitbit Versa 4"],
    },
  },
];

let mockUsersList: MockUserRecord[] = [...initialMockUsers];
let listeners: (() => void)[] = [];

export const getMockUsersList = (): MockUserRecord[] => mockUsersList;

export const getMockSingleUser = (id: string): SingleUserResponse | null => {
  const found = mockUsersList.find((u) => u.id === id);
  if (!found) return null;
  return {
    data: found.fullDetail,
    timestamp: new Date().toISOString(),
    path: `/admin/users/${id}`,
    success: true,
  };
};

export const updateMockUserInStore = (id: string, data: UpdateUserRequest) => {
  mockUsersList = mockUsersList.map((u) => {
    if (u.id === id) {
      const updatedProfile = {
        ...u.fullDetail.profile,
        ...data.profile,
      };
      return {
        ...u,
        name: data.profile.fullName || u.name,
        fullDetail: {
          ...u.fullDetail,
          profile: updatedProfile,
        },
      };
    }
    return u;
  });
  listeners.forEach((listener) => listener());
};

export const deleteMockUserInStore = (id: string) => {
  mockUsersList = mockUsersList.filter((u) => u.id !== id);
  listeners.forEach((listener) => listener());
};

export const subscribeMockUsers = (listener: () => void) => {
  listeners.push(listener);
  return () => {
    listeners = listeners.filter((l) => l !== listener);
  };
};

export const useMockUsers = () => {
  const [users, setUsers] = useState<MockUserRecord[]>(getMockUsersList);

  useEffect(() => {
    return subscribeMockUsers(() => {
      setUsers([...getMockUsersList()]);
    });
  }, []);

  return users;
};
